
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuceupindrczpmbuvwia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Y2V1cGluZHJjenBtYnV2d2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDk3ODUsImV4cCI6MjA2MTUyNTc4NX0.vzM110WCor1jp9kgj9gO0cIlN7YEVg7ZuR1wFgiW6Ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
